spring:
  application:
    name: ${APPLICATION_NAME:chargingstation-service}
    zipkin: http://${ZIPKIN_HOST:host.docker.internal}:${ZIPKIN_PORT:9411}
  kafka:
    bootstrap-servers: http://${KAFKA_HOST:host.docker.internal}:${KAFKA_PORT:9092}
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:host.docker.internal}:${MYSQL_PORT:3306}/electricalvehicle?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  redis:
    host: 'host.docker.internal'
    port: 6379
  cache:
    type: redis
    cache-names: 'chargingstations,chargingstation,chargingstations_available,chargingstation_available'
    redis:
      time-to-live: '60000'
      #key-prefix: 'ev'
  data:
    redis:
      repositories:
        enabled: false
    cache:
      type: redis
      redis:
        cache-null-values: true
        time-to-live: 10000
server:
  port: ${APPLICATION_PORT:${SERVER_PORT:0}}
  name: ${APPLICATION_NAME:gateway-service}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:host.docker.internal}:${EUREKA_PORT:8761}/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
zipkin:
  baseurl: http://${ZIPKIN_HOST:host.docker.internal}:${ZIPKIN_PORT:9411}
  sample:
    probability: 1.0